name: Pipeline Workflow

env:
  AWS_DEPLOY_ROLE_ARN: arn:aws:iam::637747527212:role/github-actions
  REGION: us-east-1
  DIST_OUTPUT_BUCKET: serverless-image-handler-images
  SOLUTION_NAME: my-serverless-image-handler
  VERSION: 1

on:
  pull_request:
    branches:
      - main
    paths:
      - 'infrastructure/**'
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - 'infrastructure/**'
  workflow_dispatch:

jobs:
  pipeline-job:
    name: Pipeline Job
    if: github.repository_owner == 'aws-solutions'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: source/constructs/infrastructure
    permissions:
      contents: read
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: install aws-cdk
        run: npm install -g aws-cdk

      - name: npm install
        run: npm install

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ env.AWS_DEPLOY_ROLE_ARN }}
          aws-region: ${{ env.REGION }}
          role-duration-seconds: 900
          role-session-name: OIDCSession
      # - name: Run CodeBuild
      #   uses: aws-actions/aws-codebuild-run-build@v1
      #   with:
      #     project-name: ${{ secrets.DISPATCHER_CODEBUILD_PROJECT_NAME }}

      #- name: CDK Bootstap
      #  if: github.ref == 'refs/heads/main'
      #  run: cdk bootstrap

      - name: CDK diff
        id: cdk-diff
        run: cdk diff

      - name: CDK Deploy
        if: github.ref == 'refs/heads/main'
        run: cdk deploy --all --require-approval never